import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
test('capture the release board and detail with isolated demonstration data', async ({ page }) => {
  const folder = fileURLToPath(new URL('../../docs/images/', import.meta.url));
  mkdirSync(folder, { recursive: true });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Project boards' }).getByRole('button', { name: /^Orbit,/ }).click();
  await page.getByRole('button', { name: /^Open Product,/ }).click();
  await expect(page.getByRole('heading', { name: 'Orbit', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Done', exact: true }).getByTestId('task-9')).toBeVisible();
  await page.screenshot({ path: folder + 'board.png', fullPage: true });
  await page.getByTestId('task-7').getByRole('button', { name: /Package a one-command installation/ }).click();
  await expect(page.getByRole('button', { name: 'Accept into Done', exact: true })).toBeVisible();
  await page.screenshot({ path: folder + 'task-detail.png', fullPage: true });
  await page.getByRole('dialog').screenshot({ path: folder + 'task-review.png' });
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.reload();
  await page.getByRole('navigation', { name: 'Project boards' }).getByRole('button', { name: /^Orbit,/ }).click();
  await page.getByRole('button', { name: /^Open Product,/ }).click();
  await expect(page.getByRole('heading', { name: 'Orbit', exact: true })).toBeVisible();
  await page.screenshot({ path: folder + 'board-dark.png', fullPage: true });
  await page.getByTestId('task-7').getByRole('button', { name: /Package a one-command installation/ }).click();
  await expect(page.getByRole('button', { name: 'Accept into Done', exact: true })).toBeVisible();
  await page.screenshot({ path: folder + 'task-detail-dark.png', fullPage: true });
  await page.getByRole('dialog').screenshot({ path: folder + 'task-review-dark.png' });
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: /^New task/ })).toBeVisible();
  await page.screenshot({ path: folder + 'board-mobile-dark.png', fullPage: true });
});

test('capture named project boards, the overview, and empty states', async ({ page }) => {
  const folder = fileURLToPath(new URL('../../docs/images/', import.meta.url));
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your boards', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /^Open Product, Orbit,/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /^Open Release, Orbit,/ })).toBeVisible();
  await page.screenshot({ path: folder + 'overview.png', fullPage: true });
  await page.getByRole('navigation', { name: 'Project boards' }).getByRole('button', { name: /^Orbit,/ }).click();
  await page.screenshot({ path: folder + 'project-boards.png', fullPage: true });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.screenshot({ path: folder + 'project-boards-dark.png', fullPage: true });
  await page.getByRole('button', { name: 'Your boards', exact: true }).first().click();
  await page.screenshot({ path: folder + 'overview-dark.png', fullPage: true });
  await page.route('**/api', async route => {
    if (route.request().postDataJSON().name === 'open_project_board') {
      await route.fulfill({ json: { data: { projects: [], boards: [], board: null, version: 'fixture' } } });
    } else await route.continue();
  });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'No Codex projects yet', exact: true })).toBeVisible();
  await page.screenshot({ path: folder + 'empty-projects-dark.png', fullPage: true });
  await page.unroute('**/api');
  await page.getByRole('button', { name: 'Refresh projects', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your boards', exact: true })).toBeVisible();
  await page.getByRole('navigation', { name: 'Project boards' }).getByRole('button', { name: 'Atlas, 0 tasks', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Atlas', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Board picker', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /^Open General,/ }).click();
  await expect(page.locator('.task-card')).toHaveCount(0);
  await page.screenshot({ path: folder + 'empty-board-dark.png', fullPage: true });
});
